balances:
  brokerage: 495000.0
  ira: 1030000.0
  roth: 105000.0
birth_year_person1: 1967
birth_year_person2: 1969
column_order:
- Year
- Person1_Age
- Person2_Age
- Filing
- Lifestyle
- Target_Spend
- Total_Spend
- Taxes_Due
- Cash_Events
- Social_Security
- IRA_Draw
- Brokerage_Draw
- Roth_Draw
- Roth_Conversion
- RMD
- IRA_Balance
- Brokerage_Balance
- Roth_Balance
- Total_Assets
draw_order: Brokerage, Roth, IRA
filing_status: MFJ
final_age_person1: 75
final_age_person2: 85
rates:
  brokerage_growth: 0.04
  inflation: 0.035
  ira_growth: 0.07
  roth_growth: 0.06
social_security:
  person1_annual_at_start: 32500.0
  person1_start_age: 62
  person2_annual_at_start: 7000.0
  person2_start_age: 62
spending:
  gogo_percent: 100.0
  gogo_years: 10
  nogo_percent: 70.0
  slow_percent: 80.0
  slow_years: 6
  start_year: 2025
  survivor_percent: 70.0
  target_spend: 120000.0
  year1_brokerage_draw: 80000.0
  year1_cash_events: -40000.0
  year1_ira_draw: 0.0
  year1_roth_draw: 0.0
  year1_spend: 40000.0
tax_health:
  aca_end_age: 65
  magi_target_base: 85000.0
  rmd_start_age: 73
  standard_deduction_base: 31500.0
