balances:
  brokerage: 538753.0
  ira: 1227023.0
  roth: 145890.0
birth_year_person1: 1967
birth_year_person2: 1969
column_order:
- Year
- Person1_Age
- Person2_Age
- Filing
- Lifestyle
- Target_Spend
- Total_Spend
- Taxes_Due
- Cash_Events
- Social_Security
- IRA_Draw
- Brokerage_Draw
- Roth_Draw
- Roth_Conversion
- RMD
- IRA_Balance
- Brokerage_Balance
- Roth_Balance
- Total_Assets
draw_order: Brokerage, IRA, Roth
filing_status: MFJ
final_age_person1: 75
final_age_person2: 85
rates:
  brokerage_growth: 0.04
  inflation: 0.035
  ira_growth: 0.07
  roth_growth: 0.06
social_security:
<<<<<<< Updated upstream
  person1_annual_at_start: 32500.0
  person1_start_age: 62
  person2_annual_at_start: 7000.0
=======
  person1_start_age: 62
>>>>>>> Stashed changes
  person2_start_age: 62
  ss_person1_benefit_annual_at_start: 32500.0
  ss_person2_benefit_annual_at_start: 7000.0
spending:
  gogo_percent: 100.0
  gogo_years: 10
  magi_conversions_annual: 0.0
  magi_conversions_projected: 0.0
  magi_conversions_years: 0.0
  magi_conversions_ytd: 0.0
  magi_gains_annual: 0.0
  magi_gains_projected: 0.0
  magi_gains_years: 0.0
  magi_gains_ytd: 0.0
  magi_income_annual: 0.0
  magi_income_projected: 0.0
  magi_income_years: 0.0
  magi_income_ytd: 0.0
  magi_losses_annual: 0.0
  magi_losses_projected: 0.0
  magi_losses_years: 0.0
  magi_losses_ytd: 0.0
  nogo_percent: 70.0
  slow_percent: 80.0
  slow_years: 6
  start_year: 2026
  survivor_percent: 70.0
  target_spend: 120000.0
  year1_brokerage_draw: 80000.0
  year1_capital_gains_to_date: 0.0
  year1_capital_losses_to_date: 0.0
  year1_cash_events: 0.0
  year1_income_to_date: 0.0
  year1_ira_draw: 0.0
  year1_magi_income: 0.0
  year1_magi_losses: 0.0
<<<<<<< Updated upstream
  year1_roth_draw: 0.0
=======
  year1_projected_capital_gains: 0.0
  year1_projected_capital_losses: 0.0
  year1_projected_income: 0.0
>>>>>>> Stashed changes
  year1_roth_conversion: 0.0
  year1_roth_draw: 0.0
  year1_spend: 80000.0
tax_health:
  aca_end_age: 65
<<<<<<< Updated upstream
  aca_expected_subsidy_monthly: 0.0
=======
>>>>>>> Stashed changes
  aca_full_premium_monthly: 0.0
  aca_full_subsidy_monthly: 0.0
  aca_magi_ceiling: 85000.0
  aca_magi_floor: 43000.0
  magi_target_base: 85000.0
  rmd_start_age: 73
  standard_deduction_base: 31500.0
