balances:
  brokerage_cash: 250000.0
  brokerage_cost_basis: 230000.0
  brokerage_unrealized_gain: 63000.0
  ira: 1227253.0
  roth: 145890.0
birth_year_person1: 1967
birth_year_person2: 1969
column_order:
- Year
- Person1_Age
- Person2_Age
- Filing
- Lifestyle
- Target_Spend
- Total_Spend
- Taxes_Due
- Social_Security
- IRA_Draw
- Brokerage_Draw
- Roth_Draw
- Roth_Conversion
- RMD
- IRA_Balance
- Brokerage_Balance
- Roth_Balance
- Total_Assets
draw_order: Brokerage, IRA, Roth
filing_status: MFJ
final_age_person1: 75
final_age_person2: 85
rates:
  brokerage_growth: 0.04
  inflation: 0.035
  ira_growth: 0.07
  roth_growth: 0.08
social_security:
  person1_annual_at_start: 32500.0
  person1_start_age: 62
  person2_annual_at_start: 7000.0
  person2_start_age: 62
spending:
  aca_extra_magi_income: 5000.0
  aca_annual_magi_income: 5000.0
  aca_magi_ceiling: 85000.0
  aca_magi_floor: 43000.0
  aca_magi_loss_offset: 500.0
  aca_magi_target: 80000.0
  aca_annual_magi_loss: 500.0
  aca_planned_roth_conversion: 35000.0
  aca_annual_roth_conversion: 35000.0
  gogo_percent: 100.0
  gogo_years: 8
  magi_conversions_projected: 0.0
  magi_conversions_years: 0.0
  magi_conversions_ytd: 15000.0
  magi_gains_projected: 0.0
  magi_gains_years: 0.0
  magi_gains_ytd: 29631.0
  magi_income_projected: 2500.0
  magi_income_years: 0.0
  magi_income_ytd: 0.0
  magi_losses_projected: 0.0
  magi_losses_years: 0.0
  magi_losses_ytd: 5332.0
  medicare_extra_magi_income: 0.0
  medicare_annual_magi_income: 0.0
  medicare_magi_ceiling: 85000.0
  medicare_magi_floor: 43000.0
  medicare_magi_loss_offset: 2000.0
  medicare_magi_target: 85000.0
  medicare_annual_magi_loss: 2000.0
  medicare_planned_roth_conversion: 50000.0
  medicare_annual_roth_conversion: 50000.0
  nogo_percent: 70.0
  slow_percent: 75.0
  slow_years: 6
  start_year: 2026
  survivor_percent: 70.0
  target_spend: 150000.0
  year1_brokerage_draw: 120000.0
  year1_capital_gains_to_date: 0.0
  year1_capital_losses_to_date: 0.0
  year1_income_to_date: 0.0
  year1_ira_draw: 0.0
  year1_extra_magi_income: 29631.0
  year1_magi_ceiling: 85000.0
  year1_magi_floor: 43000.0
  year1_magi_income: 29631.0
  year1_magi_loss_offset: 5332.0
  year1_magi_losses: 5332.0
  year1_magi_target: 80000.0
  year1_projected_capital_gains: 0.0
  year1_projected_capital_losses: 0.0
  year1_projected_income: 0.0
  year1_planned_roth_conversion: 15000.0
  year1_roth_conversion: 15000.0
  year1_roth_draw: 0.0
  year1_spend: 120000.0
tax_health:
  aca_end_age: 65
  estimated_state_deduction: 5670.0
  estimated_state_tax_rate: 0.0875
  magi_ceiling_base: 85000.0
  magi_floor_base: 43000.0
  magi_target_base: 80000.0
  medicare_magi_ceiling_base: 85000.0
  rmd_start_age: 73
  standard_deduction_base: 31500.0
